name: Grid Museum
favicon: null
layout_spectrum: 0.8227392886765301
typography_spectrum: 0.9809671270195395
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.25721829244866967
  lightness: 0.4071974135003984
  saturation: 0.7650577591266483
  rhythmicContrast: 0.7838538330979645
purpose: []
